[project]
name = "FoodReduction"
description = "Connect surplus food producers with consumers and food banks"
authors = ["Mayank jangirmayank822@gmail.com"]
telemetry = false
cache_dir = ".clarinet"
requirements = []

[contracts.FoodReduction]
path = 'contracts/FoodReduction.clar'
clarity_version = 3
epoch = 'latest'

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false


[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
